export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const REQUESTING_LOGIN = 'REQUESTING_LOGIN'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOGIN_URI = ''

export const LOGOUT = 'LOGOUT'

export const REQUEST_REGISTER = 'REQUEST_REGISTER'
export const REQUESTING_REGISTER = 'REQUESTING_REGISTER'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

